apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: puna-workspace
  namespace: puna
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: local-path
